### ISSUE TITLE
CSS border behaving strangely 

### ISSUE THREAD

**Issue by homomnomassassin** [tbolis/react-sketch#91]
When i add a border to a SketchField via a CSS style page it appears 6-8 pixles inside of the SketchField on the right side. Dose anyone know why this is and/or how to fix it?
![Capture](https://user-images.githubusercontent.com/38592693/67721519-58b54580-f99c-11e9-8f68-a26e51944902.PNG)

**Comment by frexos** [comment]
@homomnomassassin it appears that increasing the border thickness, moves the whole drawing to the left, proportionally. Indeed strange behavior, will look into this.

**Comment by frexos** [comment]
@homomnomassassin The reason behind this behavior is that the canvas dimensions are calculated and set inline. When a border is set on the parent elements, is not considered in the calculations, and the canvas element overflows. 
You may consider 3 approaches:
Setting the border via a js variable and taking it into account on the calculation of the canvas width
On class .canvas-area set your desired border and add "overflow: hidden"
On class .canvas-area instead of setting border, you may achieve the desired effect using outline. (a side-effect here is that the outline grows on the outside eliminating the surrounding space)
